Repository Sayvai-io/custom-tools, pull requests merged in 2024-02, with the labels that each got.

#64 Tools langchain 0.1
  src/sayvai_tools/tools/TTS/tool.py
  src/sayvai_tools/tools/calendar/calendar/tool.py
  src/sayvai_tools/tools/calendar/calendar_sql/tool.py
  src/sayvai_tools/tools/calendar_block/tool.py
  src/sayvai_tools/tools/date/tool.py
  src/sayvai_tools/tools/display_events/tool.py
  src/sayvai_tools/tools/forms/tool.py
  src/sayvai_tools/tools/retrive_details/retrive_email/tool.py
  src/sayvai_tools/tools/retrive_details/retrive_phone/tool.py
  src/sayvai_tools/tools/send_mail/tool.py
  src/sayvai_tools/tools/spreadsheets/sql_sheets/tool.py
  src/sayvai_tools/tools/sql_database/tool.py
  src/sayvai_tools/tools/vectordb/chromadb/tool.py
  src/sayvai_tools/tools/vectordb/pgvector/tool.py
  src/sayvai_tools/tools/vectordb/pinecone/tool.py
  src/sayvai_tools/utils/exception.py
  src/sayvai_tools/utils/voice/tts.py
Labels: enhancement

#65 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: help wanted

#66 Create FUNDING.yml
  .github/FUNDING.yml
Labels: documentation, help wanted

#69 Sanjaypranav patch 2
  setup.cfg
  src/sayvai_tools/tools/__init__.py
  src/sayvai_tools/tools/date/tool.py
  src/sayvai_tools/tools/google_calendar/__init__.py
  src/sayvai_tools/tools/google_calendar/available_slots.py
  src/sayvai_tools/tools/google_calendar/base.py
  src/sayvai_tools/tools/google_calendar/create_event.py
  src/sayvai_tools/tools/google_calendar/display_events.py
  src/sayvai_tools/tools/google_calendar/utils.py
  src/sayvai_tools/tools/google_forms/__init__.py
  src/sayvai_tools/tools/google_forms/base.py
  src/sayvai_tools/tools/google_forms/create_forms.py
  src/sayvai_tools/tools/google_forms/utils.py
  src/sayvai_tools/tools/google_sheets/__init__.py
  src/sayvai_tools/tools/google_sheets/append_data.py
  src/sayvai_tools/tools/google_sheets/base.py
  src/sayvai_tools/tools/google_sheets/create_spreedsheet.py
  src/sayvai_tools/tools/google_sheets/get_cell_values.py
  src/sayvai_tools/tools/google_sheets/utils.py
  src/sayvai_tools/tools/pdfreader/__init__.py
  src/sayvai_tools/tools/vectordb/chromadb/tool.py
  src/sayvai_tools/utils/__init__.py
  src/sayvai_tools/utils/database/dbchain.py
  src/sayvai_tools/utils/database/sheetschain.py
  src/sayvai_tools/utils/pdfreader/__init__.py
  src/sayvai_tools/utils/system/properties/__init__.py
  templates/calendar-events/gcalendar/calendaragent.py
  templates/calendar-events/gcalendar/create_event.py
Labels: bug

#71 youtube comments tool
  src/sayvai_tools/tools/__init__.py
  src/sayvai_tools/tools/google_sheets/create_spreadsheet.py
  src/sayvai_tools/tools/google_sheets/update_spreadsheet.py
  src/sayvai_tools/tools/youtube/__init__.py
  src/sayvai_tools/tools/youtube/base.py
  src/sayvai_tools/tools/youtube/comment_threads/__init__.py
  src/sayvai_tools/tools/youtube/comment_threads/add_comment.py
  src/sayvai_tools/tools/youtube/comment_threads/list_comments.py
  src/sayvai_tools/tools/youtube/comments/__init__.py
  src/sayvai_tools/tools/youtube/comments/list_comments.py
  src/sayvai_tools/tools/youtube/comments/reply_to_comment.py
  src/sayvai_tools/tools/youtube/utils.py
  templates/google_sheets/append_data.py
  templates/google_sheets/get_cell_values.py
  templates/google_sheets/update_spreedsheets.py
  templates/youtube/comments/add_comment.py
  templates/youtube/comments/list_comment_replies.py
  templates/youtube/comments/list_comments.py
  templates/youtube/comments/reply_to_comment.py
Labels: new tool

#74 Add langchain-pinecone package and update version numbers 👨‍🏭
  .github/workflows/python-package-ci-cd.yml
  .github/workflows/python-package.yml
  Makefile
  poetry.lock
  pyproject.toml
  src/sayvai_tools/tools/__init__.py
  src/sayvai_tools/tools/date/tool.py
  src/sayvai_tools/tools/loader.py
  src/sayvai_tools/tools/vectordb/__init__.py
  src/sayvai_tools/tools/vectordb/chromadb/__init__.py
  src/sayvai_tools/tools/vectordb/chromadb/tool.py
  src/sayvai_tools/tools/vectordb/pgvector/__init__.py
  src/sayvai_tools/tools/vectordb/pgvector/tool.py
  src/sayvai_tools/tools/vectordb/pinecone/__init__.py
  src/sayvai_tools/tools/vectordb/pinecone/tool.py
  tests/test_import.py
  tests/test_tools/test_getdate.py
Labels: good first issue, new tool, pytest for tools

#75 Add twine to project dependencies
  .github/workflows/python-package-ci-cd.yml
Labels: documentation

#76 Update twine installation method
  .github/workflows/python-package-ci-cd.yml
Labels: bug

#77 Add PyPI upload step to CI/CD workflow
  .github/workflows/python-package-ci-cd.yml
Labels: enhancement

#78 Update python-package-ci-cd.yml
  .github/workflows/python-package-ci-cd.yml
Labels: documentation

#79 Pytest
  .github/workflows/python-package-ci-cd.yml
Labels: enhancement

#81 updated sqldatabase 🤖
  docs/introduction.mdx
  src/sayvai_tools/tools/sql_database/tool.py
  templates/calendar-events/gcalendar/agentcalendar.py
Labels: bug
